name: Deploy

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile # equivalent to pnpm ci

      - name: Create env files
        run: |
          echo "Creating .env file for client"
          echo JWT_SIGNATURE=${{secrets.JWT_SIGNATURE}} > apps/client/.env
          echo RECAPTCHA_SECRET_KEY=${{ secrets.RECAPTCHA_SECRET_KEY }} >> apps/client/.env
          echo ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }} >> apps/client/.env
          echo BASE_URL=${{ secrets.BASE_URL }} >> apps/client/.env

          echo ENV=${{secrets.ENV}} > apps/server/.env
          echo BASE_URL=${{ secrets.BASE_URL }} >> apps/server/.env
          echo DB_CONNECTION=${{ secrets.DB_CONNECTION }} >> apps/server/.env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> apps/server/.env
          echo DB_NAME=${{ secrets.DB_NAME }} >> apps/server/.env
          echo JWT_SIGNATURE=${{secrets.JWT_SIGNATURE}} >> apps/server/.env
          echo POSTMARK_API_TOKEN=${{secrets.POSTMARK_API_TOKEN}} >> apps/server/.env
          echo AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}} >> apps/server/.env
          echo AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} >> apps/server/.env
          echo AWS_BUCKET_REGION=${{secrets.AWS_BUCKET_REGION}} >> apps/server/.env
          echo AWS_BUCKET_NAME=${{secrets.AWS_BUCKET_NAME}} >> apps/server/.env
          echo RP_ID=${{secrets.RP_ID}} >> apps/server/.env

      - name: Copy app
        run: |
            cp -r apps/ package.json packages/ pnpm-lock.yaml pnpm-workspace.yaml /var/www/brailler.daishodesign.com/

      - name: Build app
        run: |
            cd /var/www/brailler.daishodesign.com/
            pnpm install --frozen-lockfile --prod
            pnpm run build

      - name: Deploy app
        run: |
            pm2 delete fc || true
            pm2 start npm --name fc -- run prod
