name: Deploy

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile # equivalent to pnpm ci

      - name: Create env files
        run: |
          echo "Creating .env file for client"
          cd apps/client
          echo JWT_SIGNATURE=${{secrets.JWT_SIGNATURE}} > .env
          echo RECAPTCHA_SECRET_KEY=${{ secrets.RECAPTCHA_SECRET_KEY }} >> .env
          echo ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }} >> .env
          echo BASE_URL=${{ secrets.BASE_URL }} >> .env

          cd ../server
          echo ENV=${{secrets.ENV}} > .env
          echo BASE_URL=${{ secrets.BASE_URL }} >> .env
          echo DB_CONNECTION=${{ secrets.DB_CONNECTION }} >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          echo JWT_SIGNATURE=${{secrets.JWT_SIGNATURE}} >> .env
          echo POSTMARK_API_TOKEN=${{secrets.POSTMARK_API_TOKEN}} >> .env
          echo AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}} >> .env
          echo AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} >> .env
          echo AWS_BUCKET_REGION=${{secrets.AWS_BUCKET_REGION}} >> .env
          echo AWS_BUCKET_NAME=${{secrets.AWS_BUCKET_NAME}} >> .env
          echo RP_ID=${{secrets.RP_ID}} >> .env

      - name: Build
        run: pnpm run build

      - name: Deploy app
        run: |
            cp -r apps/server/ /var/www/fem.daishodesign.com/
            
            mkdir -p /var/www/fem.daishodesign.com/client/
            cp apps/client/.env /var/www/fem.daishodesign.com/client/
            cp -r apps/client/build/ /var/www/fem.daishodesign.com/client/

            pm2 stop fc || true

            cd /var/www/fem.daishodesign.com/server
            pm2 start pnpm --name "fc_server" -- exec ts-node /var/www/fem.daishodesign.com/server/index.ts

            cd /var/www/fem.daishodesign.com/client
            pm2 start "node build" --name "client" --env ORIGIN=https://brailler.daishodesign.com PORT=8895
